### PR TITLE
chore(release): bump version to 2.0.0

### PR DESCRIPTION
**Pull request by ofrobots**
[release notes](https://github.com/googleapis/nodejs-logging/releases/edit/untagged-717f572534baf338c40c)

This release is needed to fix for https://github.com/googleapis/nodejs-error-reporting/issues/155, which requires a new version of `google-cloud/common` to be picked up. 

Without spinning a release:
```sh
~/src/veneer/nodejs-logging-winston $ npx npm-why @google-cloud/common
npx: installed 10 in 2.22s

  Who required @google-cloud/common:

  @google-cloud/logging-winston > @google-cloud/logging > @google-cloud/common@0.16.2
  @google-cloud/logging-winston > @google-cloud/logging > @google-cloud/common-grpc > @google-cloud/common@0.17.0
```
We need to be able to pick up `common@0.20.2`.

---
This release is semver major release because it drops support for Node 4.x and 9.x. Apart from that there should be no other breaking changes.

# Notable changes
* Node.js 4.x and 9.x are no longer supported (#123)

# Commits
* 876e32d chore(release): bump version to 2.0.0
* f7518e1 Re-generate library using /synth.py (#148)
* dde2613 Re-generate library using /synth.py (#147)
* ae3808c fix(deps): update dependency yargs to v12 (#146)
* 268dab5 Re-generate library using /synth.py (#145)
* bca99ad chore(deps): update dependency uuid to v3.3.0 (#142)
* 19f0d4f chore(deps): update dependency sinon to v6.0.1 (#141)
* f2a5811 Configure Renovate (#129)
* b60f986 Re-generate library using /synth.py (#140)
* a80056a refactor: drop repo-tool as an exec wrapper (#139)
* faa3b6e chore: update sample lockfiles (#138)
* ea534d2 chore(package): update eslint to version 5.0.0 (#134)
* b9e3de4 Re-generate library using /synth.py (#137)
* 4bd42b3 fix: update linking for samples (#136)
* d135381 Re-generate library using /synth.py (#135)
* 01ec04e chore: regenerate the library, upgrade gax
* 654884e Update synth.py, removing generate-scaffolding (#130)
* 7feb300 refactor: update to latest google-auth-library and nodejs-common (#128)
* 267a0fc Create synth script for nodejs-logging (#127)
* 6e26499 fix(package): update @google-cloud/common-grpc to version 0.7.1 (#126)
* c1888d7 refactor: drop dependency on string-format-obj (#124)
* 80862b4 chore: update many dependencies (#122)
* 1ccf7e4 fix: drop support for node 4.x and 9.x (#123)
* 3c4b94c chore(package): update nyc to version 12.0.2 (#117)
* 27f1d04 chore: lock files maintenance (#114)
* 530a155 chore: the ultimate fix for repo-tools EPERM (#113)
* 2a8524f chore: timeout for system test (#112)
* 161711a chore: lock files maintenance (#109)
* 3747e38 chore: test on node10 (#107)
* 807733f chore: lock files maintenance (#106)
* 962fd30 chore: one more workaround for repo-tools EPERM (#103)
* 1151caa chore: workaround for repo-tools EPERM (#101)
* b3bece4 Update @google-cloud/common to the latest version 🚀 (#100)
* cafac75 chore: make samples depend on the current version (#99)
* 6f6eee1 Update google-auto-auth (#98)
* dff5d1b chore: setup nighty build in CircleCI (#97)

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Should `samples/package.json` depend on 2.0.0 as well?

https://github.com/googleapis/nodejs-logging/blob/f7518e1a0638e9da9ec2489f4ec18342afbaab4b/samples/package.json#L18

**Comment by ofrobots** [comment]
@alexander-fenster I can bump that, but wouldn't renovate take care of it after the fact?

**Review by JustinBeckwith — APPROVED** [review]

**Comment by stephenplusplus** [comment]
Just want to confirm we are saving https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2556 for 3.0.0?

**Comment by alexander-fenster** [comment]
@ofrobots Renovate will (should) detect that, but only after 2.0.0 is released. If we bump dependency version before the release, samples tests will be run against the latest code because of `npm link` magic (and it might in theory catch a bug before it gets released).

**Comment by ofrobots** [comment]
@alexander-fenster the motivation makes sense, I'll try to do it for the next bump. And maybe the release script (releasetool?) can automate this manual work going forward. I don't think this is a but issue for this change as each commit is already getting tested against samples. This commit only has the `package.json` change.

**Comment by ofrobots** [comment]
@stephenplusplus I'll let @JustinBeckwith answer that one. I need a release ASAP to be able to fix  googleapis/nodejs-error-reporting#155, and if we are going to release from current master, given the commits that are queued up, this one *has* to be a 2.0.0.

The other alternative would to be cut a separate branch for the 1.x release line, cherry pick the relevant fixes and release that. Either way, being able to make a release soon would be good.

**Comment by ofrobots** [comment]
Hi @JustinBeckwith. This has been merged but not released yet. This is blocking https://github.com/googleapis/nodejs-error-reporting/issues/155, which is a P1 issue that we must resolve soon.

What's the plan for release?

**Comment by JustinBeckwith** [comment]
I am confused.  It looks like it's been released?

**Comment by ofrobots** [comment]
Nopes. https://www.npmjs.com/package/@google-cloud/logging?activeTab=versions

**Comment by ofrobots** [comment]
It didn't release apparently because of this a system test failure: https://circleci.com/workflow-run/b71c58c4-a95e-4f3d-a7c7-10662b623b44

**Comment by ofrobots** [comment]
Kicked ⚽️🏃‍♂️ the job a few times and it ended up getting published 🤪.

**Pull request merged**
