### PR TITLE
chore: add api_shortname and library_type to repo metadata

### PR DESCRIPTION
**Pull request by parthea**
Update .repo-metadata.json as required by go/library-data-integrity

### CODE REVIEW

**Review by losalex — APPROVED** [review]
lgtm

**Review by losalex — CHANGES_REQUESTED** [review]
Please address README related comment

**Comment by bcoe** [comment]
@losalex the logic for warning on README updates is giving a false positive in this case, the README is generated automatically from `.repo-metadata.json`, so this is not a manual change.

**Review by bcoe — APPROVED** [review]

**Review by losalex — APPROVED** [review]
lgtm

**Comment by losalex** [comment]
> @losalex the logic for warning on README updates is giving a false positive in this case, the README is generated automatically from `.repo-metadata.json`, so this is not a manual change.

Sure, thanks @bcoe for clarification!

**Review by bcoe — APPROVED** [review]

**Pull request merged**
