### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by stephenplusplus**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Assigned to @lukesneeringer since we need a GAPIC regen for the docs to work.

**Comment by jmdobry** [comment]
And I'll need to do a final review and internal staging of the docs before we cut the release.

**Comment by lukesneeringer** [comment]
Waiting on @jmdobry for the final pass. Could we do a semver-minor bump rather than a semver-patch bump? So, 1.1.0?

**Comment by lukesneeringer** [comment]
Proposed release notes forthcoming in the next comment.

**Comment by lukesneeringer** [comment]
[release level](https://cloud.google.com/terms/launch-stages)

## Features

#### Runnable samples

There are now runnable samples in the `samples/` directory. These samples demonstrate the use of this API and offer an additional resource for getting started. These also power the readme, and are automatically tested to ensure that they are up-to-date and correct.

## Implementation Details

  * Change to a new linter (ESLint) and code style formatter (prettify).
  * Update docs to use [JSDoc 3](https://usejsdoc.org).
  * Migrate to the `googleapis/nodejs-logging` repository.

**Comment by lukesneeringer** [comment]
Checking on why CircleCI does not seem to be running on your fork. That is probably a misconfiguration on my part.

Also, this should block on #10 and #11.

**Comment by jmdobry** [comment]
I'm going to do a final pass on the JSDocs right now.

**Comment by lukesneeringer** [comment]
This is ready as soon as tests pass and someone gives me a green checkmark.
I am going to stage the release notes in the draft interface now.

**Comment by lukesneeringer** [comment]
I just realized, **I** am the green checkmark giver for this. :-D

**Pull request merged**
