### PR TITLE
fix!: users can log httprequest logs without providing a log message

### LINKED ISSUE #929: entry: httprequest without a log message should format correctly
Reported from user issue b/ 172339240

**To repro:** 
```javascript
e = log.entry(httprequest-data, nil)
log.write(e)
```

**yields** 
```JSON
jsonPayload: {
  httpRequest: {
   requestMethod: "get"    
  }
 }
```

**should be**
```
httpRequest: {
   requestMethod: "get"    
}
// jsonPayload is nil
```

This would be a breaking change for users who are used to this behavior, but it would make this client consistent with other languages & product spec

### PR DESCRIPTION
**Pull request by freelerobot**
Fixes #929 🦕

According to specs and [docs](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry), users should be able to log `httpRequest` type logs independently of a log message. 

In this case, the log message (jsonPayload field) can just show up as `{}`. And of course, `jsonPayload` field should not contain the `httpRequest` data.

Note:
- Users can now log `entry(metadata.httprequest, nil)` and jsonPayload will show up as `{}`
- Users can still log `entry(nil, message)`
- Users can still log `entry(metadata, message)` - regular case
- See test cases

Solves customer issue: b/172339240

### CODE REVIEW

**Review by daniel-sanche — APPROVED** [review]

**Comment by bcoe** [comment]
@nicoleczhu this seems like the right fix to me 👍 

The only thing we should be mindful of, is that we try to keep breaking changes to once every year or so. I think we could choose to do a breaking change of the library now, but it might be good to see if there are any other breaking changes we want to make at the same time.

**Comment by nicoleczhu** [comment]
> @nicoleczhu this seems like the right fix to me 👍
> 
> The only thing we should be mindful of, is that we try to keep breaking changes to once every year or so. I think we could choose to do a breaking change of the library now, but it might be good to see if there are any other breaking changes we want to make at the same time.

Makes sense! I was hesitant to release this for that very reason. I'm gonna work on a few more PRs this month, and see if we can bundle a breaking update containing multiple new features/fixes. Tagging this one as `do not merge` for now.

**Review by stephenplusplus — APPROVED** [review]

**Review by bcoe — APPROVED** [review]

**Review by bcoe — COMMENTED** [review]
Could we squint, and not call this a breaking change, since I believe we're making it work as intended?

Someone setting `httpRequest` would expect this meta information to be handled differently right?

**Comment by nicoleczhu** [comment]
> Could we squint, and not call this a breaking change, since I believe we're making it work as intended?
> 
> Someone setting `httpRequest` would expect this meta information to be handled differently right?

I think most new users would expect this fix as the default behavior. 

It will only be breaking for users who were aware of the bug on our end && were custom handling the poorly structured logs themselves.

**Comment by bcoe** [comment]
@nicoleczhu it's okay for us to release a major of logging, if you think this is likely to bite people.

**Review by bcoe — APPROVED** [review]

**Pull request merged**
